name: machine-learning-env
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - python=3.9.18
  - nvidia::cudatoolkit
  - pytorch-cuda=12.1
  - matplotlib
  - torchvision=0.16.0=py39_cu121
  - pandas
  - pip
  - pip:
      - idx2numpy
      - tqdm
